stages:
  - build

# We'll probably want to run 2 grafanas eventually where by
# one can be edited and we take those chagnes and do a formal
# grafana release
build-develop-grafana:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/grafana:latest" .
    - docker tag "$CI_REGISTRY/grafana:latest" "$CI_REGISTRY/grafana:develop-$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY/grafana:latest"
    - docker push "$CI_REGISTRY/grafana:develop-$CI_COMMIT_SHORT_SHA"
  only:
    - master
