{
 "title": "Backup Utility Metrics - Postgres and Media",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Postgres - Successful Hourly Backups",
   "type": "graph",
   "description": "Backup count should increase by one, for each database, per hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-prod-.*\",status=\"success\",type=\"postgres\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Postgres - Successful Hourly Uploads",
   "type": "graph",
   "description": "Upload count should increase by one per hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_utility_upload_to_blob_count_total{resource=\"binkuksouthprod\",schedule=\"hourly\",type=\"postgres\"}",
     "legendFormat": "{{resource}} {{type}} {{schedule}}"
    }
   ]
  },
  {
   "title": "Postgres - Failed Hourly Backups",
   "type": "graph",
   "description": "Failed backups should not be increasing by the hour. Historical failures will show as a flat line.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-prod-.+\",status=\"failed\",type=\"postgres\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Postgres - SQL Dump File Size",
   "type": "graph",
   "description": "File size of the backup over time. Shouldn't change wildly.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backup_utility_file_size{resource=~\"bink-uksouth-prod-.+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Preprod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres - Successful Hourly Backups",
     "type": "graph",
     "description": "Backup count should increase by one, for each database, per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-preprod-.*\",status=\"success\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - Successful Hourly Uploads",
     "type": "graph",
     "description": "Upload count should increase by one per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_upload_to_blob_count_total{resource=\"binkuksouthpreprod\",schedule=\"hourly\",type=\"postgres\"}",
       "legendFormat": "{{resource}} {{type}} {{schedule}}"
      }
     ]
    },
    {
     "title": "Postgres - Failed Hourly Backups",
     "type": "graph",
     "description": "Failed backups should not be increasing by the hour. Historical failures will show as a flat line.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-preprod-.+\",status=\"failed\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - SQL Dump File Size",
     "type": "graph",
     "description": "File size of the backup over time. Shouldn't change wildly.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_size{resource=~\"bink-uksouth-preprod-.+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres - Successful Hourly Backups",
     "type": "graph",
     "description": "Backup count should increase by one, for each database, per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-staging-.*\",status=\"success\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - Successful Hourly Uploads",
     "type": "graph",
     "description": "Upload count should increase by one per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_upload_to_blob_count_total{resource=\"binkuksouthstaging\",schedule=\"hourly\",type=\"postgres\"}",
       "legendFormat": "{{resource}} {{type}} {{schedule}}"
      }
     ]
    },
    {
     "title": "Postgres - Failed Hourly Backups",
     "type": "graph",
     "description": "Failed backups should not be increasing by the hour. Historical failures will show as a flat line.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-staging-.+\",status=\"failed\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - SQL Dump File Size",
     "type": "graph",
     "description": "File size of the backup over time. Shouldn't change wildly.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_size{resource=~\"bink-uksouth-staging-.+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dev",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres - Successful Hourly Backups",
     "type": "graph",
     "description": "Backup count should increase by one, for each database, per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-dev-.*\",status=\"success\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - Successful Hourly Uploads",
     "type": "graph",
     "description": "Upload count should increase by one per hour.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_upload_to_blob_count_total{resource=\"binkuksouthdev\",schedule=\"hourly\",type=\"postgres\"}",
       "legendFormat": "{{resource}} {{type}} {{schedule}}"
      }
     ]
    },
    {
     "title": "Postgres - Failed Hourly Backups",
     "type": "graph",
     "description": "Failed backups should not be increasing by the hour. Historical failures will show as a flat line.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_count_total{resource=~\"bink-uksouth-dev-.+\",status=\"failed\",type=\"postgres\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Postgres - SQL Dump File Size",
     "type": "graph",
     "description": "File size of the backup over time. Shouldn't change wildly.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "backup_utility_file_size{resource=~\"bink-uksouth-dev-.+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}