{
 "title": "Barclays SLA Info",
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "title": "Register - service - POST",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Retrieve Cards - membership-cards - GET",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.125\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.375\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Retrieve Card Details - membership-card - GET",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\"}))) * 10",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Retrieve Plan Information - membership-plans - GET",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.125\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.375\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-plans\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Retrieve LinkedPayment Card - payment-cards - GET",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"GET\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Add / Join Membership  - membership-cards - POST",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Enrol Payment Card - payment-cards - POST",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"POST\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "De-register - service - DELETE",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Unenroll Payment Card - payment-cards - DELETE",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Remove Membership Card  - membership-cards - DELETE",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(django_http_requests_latency_seconds_by_view_method_sum{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\"})) / (sum(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\"}))) * 1000",
     "legendFormat": "Average Response time (MS)"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.15\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 95\n",
     "legendFormat": "95th"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\", le=\"0.45\"} [2m])) by (job) / sum(rate(django_http_requests_latency_seconds_by_view_method_count{kubernetes_cluster=\"prod0\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\", method=\"DELETE\"} [2m])) by (job) * 100 > 99",
     "legendFormat": "99th "
    }
   ]
  }
 ]
}