{
 "title": "Checkly",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "/membership_cards",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*prod.*\",check_name=\"/membership_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "/membership_plans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*prod.*\",check_name=\"/membership_plans\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Up Time %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(checkly_check_status{tags=~\".*prod.*\"}) * 100",
       "legendFormat": "Status Up/Down"
      },
      {
       "expr": "avg(checkly_check_degraded_status{tags=~\".*prod.*\"}) * 100",
       "legendFormat": "Degraded"
      }
     ]
    },
    {
     "title": "/payment_cards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*prod.*\",check_name=\"/membership_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "/membership_cards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*staging.*\",check_name=\"/membership_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "/membership_plans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*staging.*\",check_name=\"/membership_plans\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "/payment_cards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*staging.*\",check_name=\"/payment_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Up Time %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(checkly_check_status{tags=~\".*staging.*\"}) * 100",
       "legendFormat": "Status Up/Down"
      },
      {
       "expr": "avg(checkly_check_degraded_status{tags=~\".*staging.*\"}) * 100",
       "legendFormat": "Degraded"
      }
     ]
    }
   ]
  },
  {
   "title": "Development",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "/membership_cards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*dev.*\",check_name=\"/membership_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "/membership_plans",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*dev.*\",check_name=\"/membership_plans\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "/payment_cards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "checkly_check_result{tags=~\".*dev.*\",check_name=\"/payment_cards\"}",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Up Time %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(checkly_check_status{tags=~\".*dev.*\"}) * 100",
       "legendFormat": "Status Up/Down"
      },
      {
       "expr": "avg(checkly_check_degraded_status{tags=~\".*dev.*\"}) * 100",
       "legendFormat": "Degraded"
      }
     ]
    }
   ]
  }
 ]
}