{
 "title": "Elasticsearch Index Ingress",
 "description": "Hows how many items per minute are being accepted",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Index writes per minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Azure Firewall Writes/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "5m",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Ingress NGINX Writes/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "5m",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Azure Active Directory Writes/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "5m",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Log Writes/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:38",
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "5m",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:36", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Azure FrontDoor Writes/min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "5m",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  { "title": "Index write count per timespan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Azure Firewall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:48",
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:46", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Ingress NGINX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:117",
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:115", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Azure Active Directory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:71",
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:69", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Log Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:38",
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:36", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Azure FrontDoor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:94",
       "field": "time",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:92", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "time"
    }
   ]
  }
 ]
}