{
 "title": "Elasticsearch",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node elasticsearch-01",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{name=\"monitoring-elasticsearch-01\"}"
    }
   ]
  },
  {
   "title": "Node elasticsearch-02",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{name=\"monitoring-elasticsearch-02\"}"
    }
   ]
  },
  {
   "title": "Node elasticsearch-03",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_exporter_build_info{name=\"monitoring-elasticsearch-03\"}"
    }
   ]
  }
 ]
}