{
 "title": "Eventhub Log Streaming",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventhub",
    "label": "Eventhub",
    "query": "label_values(eh2es_event_process_time_bucket, eventhub)"
   }
  ]
 },
 "panels": [
  {
   "title": "Event processing time - $eventhub",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "eventhub",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(eh2es_event_process_time_bucket{eventhub=\"$eventhub\"}[5m])) by (le))",
     "legendFormat": "Total time"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(eh2es_elasticsearch_ingest_time_bucket{eventhub=\"$eventhub\"}[5m])) by (le))",
     "legendFormat": "Elasticsearch ingest time"
    }
   ]
  },
  {
   "title": "Elasticsearch records written / m - $eventhub",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "eventhub",
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(eh2es_elasticsearch_records_write_total{eventhub=\"$eventhub\"}[2m])) by (eventhub) * 60",
     "legendFormat": "Records ingested"
    }
   ]
  },
  {
   "title": "EventHub events consumed / m - $eventhub",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "eventhub",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(eh2es_eventhub_records_read_total{eventhub=\"$eventhub\"}[2m])) by (eventhub) * 60",
     "legendFormat": "Events"
    }
   ]
  }
 ]
}