{
 "title": "Hermes DevOps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n# HTTP Request Response Times"
  },
  {
   "title": "Membership Card",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_card/",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Membership Cards",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_cards/",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "graph",
   "description": "endpoint: /ubiquity/service/",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Payment Card",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_card",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-card\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Payment Cards",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_cards",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Membership Plans",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_plans",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-plans\", job=\"hermes\", channel=\"com.barclays.bmb\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "\n# HTTP Request Response Codes"
  },
  {
   "title": "GET",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"GET\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"PUT\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "POST",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"POST\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"DELETE\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"com.barclays.bmb\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  }
 ]
}