{
 "title": "Hermes Pods",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "content": "\n# Hermes\n\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"hermes-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 }, "content": "\n# Atlas\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"atlas-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 }, "content": "\n# Europa\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"europa-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 }, "content": "\n# Hades\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"hades-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 }, "content": "\n# Harmonia\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"harmonia-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 }, "content": "\n# Iris\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"iris\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"iris\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"iris\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"iris-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 }, "content": "\n# Lethe\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"lethe\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"lethe\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"lethe\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"lethe-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}