{
 "title": "Hermes Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   { "name": "channel", "label": "Channel", "query": "label_values(channel)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n# HTTP Request Response Times"
  },
  {
   "title": "Service - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/service/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Service - DELETE",
   "type": "graph",
   "description": "endpoint: /ubiquity/service/",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Cards - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_cards/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Card - DELETE",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_cards/",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Card - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_card/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"GET\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"GET\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Cards - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_card/",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"POST\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"POST\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Plans - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_plans",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-plans\", job=\"hermes\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-plans\", job=\"hermes\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Cards - PATCH",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_plans",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-cards\", job=\"hermes\", channel=\"$channel\", method=\"PATCH\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-cards\", job=\"hermes\", channel=\"$channel\", method=\"PATCH\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Payment Cards - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_cards",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Payment Card - DELETE",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_cards",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "content": "\n# HTTP Request Response Codes"
  },
  {
   "title": "GET",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"GET\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"PUT\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "POST",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"POST\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"DELETE\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view) ",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service\", channel=\"$channel\"}[2m])) by (status, view)",
     "legendFormat": "{{status}}--{{view}}"
    }
   ]
  }
 ]
}