{
 "title": "Loyalty Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   { "name": "scheme", "label": "Loyalty Scheme", "query": "label_values(scheme)" },
   { "name": "channel", "label": "Channel", "query": "label_values(channel)" }
  ]
 },
 "panels": [
  {
   "title": "Enrol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Enrol\", scheme=\"$scheme\", channel=\"$channel\"} [2m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Link",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Link\", scheme=\"$scheme\", channel=\"$channel\"} [2m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Multi Wallet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Multi Wallet\", scheme=\"$scheme\", channel=\"$channel\"} [2m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Wallet Only",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Wallet Only\", scheme=\"$scheme\", channel=\"$channel\"} [2m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}