{
 "title": "Testing QA Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  { "title": "LOY1380", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "membership_card_status_change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_status_change_total{kubernetes_cluster=\"$cluster\"}) by (scheme, status_change, channel)",
     "legendFormat": "{{scheme}} -- {{channel}} -- {{status_change}}"
    }
   ]
  },
  {
   "title": "LOY-1515",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Iris response by status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(iris_response_by_status_total{kubernetes_cluster=\"$cluster\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LOY-1516",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lethe requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(lethe_request_by_template_total{kubernetes_cluster=\"$cluster\"} ) by (template)",
       "legendFormat": "{{template}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DevOps - 1211",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ticket",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# DEVOPS-1211\n* MER-796\n* MER-788\n* MER-784\n\n\n"
    },
    {
     "title": "Log_in_success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(log_in_success_total) by (slug,kubernetes_cluster)",
       "legendFormat": "{{slug}} -- {{kubernetes_cluster}}"
      }
     ]
    },
    {
     "title": "Log_in_fail",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(log_in_fail_total) by (slug,kubernetes_cluster)",
       "legendFormat": "{{slug}} -- {{kubernetes_cluster}}"
      }
     ]
    },
    {
     "title": "Response code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(request_latency_seconds_count) by (slug, response_code, kubernetes_cluster)",
       "legendFormat": "{{response_code}} -- {{slug}} -- {{kubernetes_cluster}}"
      }
     ]
    },
    {
     "title": "register_success",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(register_success_total) by (slug, kubernetes_cluster, channel)",
       "legendFormat": "{{slug}} -- {{channel}} --  {{kubernetes_cluster}}"
      }
     ]
    },
    {
     "title": "register_fail",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(register_fail_total) by (slug,kubernetes_cluster, channel)",
       "legendFormat": "{{slug}} -- {{channel}} --  {{kubernetes_cluster}}"
      }
     ]
    },
    {
     "title": "request_latency_seconds_bucket",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50,sum(rate(request_latency_seconds_bucket{slug=\"harvey-nichols\"} [5m])) by (le, slug, kubernetes_cluster, endpoint, response_code))",
       "legendFormat": "{{slug}} --  {{response_code}} -- {{kubernetes_cluster}} -- {{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LOY1432",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "VOP activation status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hermes_current_vop_activation_status_total{kubernetes_cluster=\"$cluster\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LOY1479",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hermes_current_users_total{kubernetes_cluster=\"$cluster\", client_app=\"Barclays Mobile Banking\"}"
      }
     ]
    },
    {
     "title": "Current Payment Cards",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hermes_current_payment_cards_total{kubernetes_cluster=\"$cluster\", client_app=\"Barclays Mobile Banking\"}",
       "legendFormat": "{{client_app}}"
      }
     ]
    },
    {
     "title": "Current Membership Cards",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hermes_current_membership_cards_total{kubernetes_cluster=\"$cluster\", client_app=\"Barclays Mobile Banking\"}",
       "legendFormat": "{{client_app}}"
      }
     ]
    }
   ]
  }
 ]
}