{
 "title": "Pod Resource Info",
 "tags": [
  "kubernetes",
  "pod"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(container_cpu_usage_seconds_total, kubernetes_cluster)"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total{kubernetes_cluster=\"$env\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_usage_seconds_total{kubernetes_cluster=\"$env\", namespace=\"$ns\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_usage_seconds_total{kubernetes_cluster=\"$env\", namespace=\"$ns\", pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod=\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Time spent CPU throttled ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Pod network usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Container Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Container \"$container\" CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"$container\",pod=\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Container \"$container\" time spent CPU throttled ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container_name=\"$container\",pod=\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Container \"$container\" memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"$container\",pod=\"$pod\"})"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_name=\"$container\",pod=\"$pod\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}