{
 "title": "RabbitMQ Overview",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(rabbitmq_identity_info, kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\"}, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ready messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Incoming messages /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_channel_messages_published_total * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) + sum(rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) + sum(rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) + sum(rate(rabbitmq_channel_get_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) + sum(rate(rabbitmq_channel_get_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory available before publishers blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(rabbitmq_resident_memory_limit_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) - (rabbitmq_process_resident_memory_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Disk space available before publishers blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_disk_space_available_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "File descriptors available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rabbitmq_process_max_fds * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) - (rabbitmq_process_open_fds * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "TCP sockets available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rabbitmq_process_max_tcp_sockets * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) -\n(rabbitmq_process_open_tcp_sockets * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Queued Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Messages ready to be delivered to consumers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages pending consumer acknowledgement",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster, rabbitmq_node)  rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Incoming Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Messages published /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages confirmed to publishers /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_confirmed_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages unconfirmed to publishers /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_unconfirmed[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Outgoing Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Messages delivered /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    (rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) +\n     (rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"})\n     ) by(kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Messages acknowledged /s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_acked_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{kubernetes_cluster=\"$kubernetes_cluster\",kubernetes_namespace=\"$namespace\"}) by(kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}