{
 "title": "Staging",
 "description": "VMs, Postgres, Redis, Storage Accounts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Staging Worker CPU Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "percentage_cpu_percent_average{resource_group=\"uksouth-staging-k0\",resource_name=\"staging0-worker00\"}",
     "legendFormat": "{{resource_name}}"
    },
    {
     "expr": "percentage_cpu_percent_average{resource_group=\"uksouth-staging-k0\",resource_name=\"staging0-worker01\"}",
     "legendFormat": "{{resource_name}}"
    },
    {
     "expr": "percentage_cpu_percent_average{resource_group=\"uksouth-staging-k0\",resource_name=\"staging0-worker02\"}",
     "legendFormat": "{{resource_name}}"
    },
    {
     "expr": "percentage_cpu_percent_average{resource_group=\"uksouth-staging-k0\",resource_name=\"staging0-worker03\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Staging Postgres/Redis CPU Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_percent_percent_average{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Postgres"
    },
    {
     "expr": "serverload_percent_average{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Redis"
    }
   ]
  },
  {
   "title": "Staging Virtual Machine CPU Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "percentage_cpu_percent_average{resource_group=\"uksouth-staging-k0\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Staging Postgres/Redis Miscellaneous",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_connections_count_total{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Postgres Active Connections"
    },
    {
     "expr": "connections_failed_count_total{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Postgres Connections Failed"
    },
    {
     "expr": "connectedclients_count_total{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Redis Connected Clients"
    },
    {
     "expr": "errors_count_total{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Redis Errors"
    }
   ]
  },
  {
   "title": "Staging Storage Account Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress_bytes_min{resource_group=\"uksouth-staging\"}",
     "legendFormat": "{{resource_name}} Ingress"
    }
   ]
  },
  {
   "title": "Staging Virtual Machine Network Packets Sent/Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "packetssentrate_count_total{resource_group=\"uksouth-staging-k0\"}",
     "legendFormat": "{{resource_name}} Sent"
    },
    {
     "expr": "packetsreceivedrate_count_total{resource_group=\"uksouth-staging-k0\"}",
     "legendFormat": "{{resource_name}} Received"
    }
   ]
  }
 ]
}