{
 "title": "PROD TV Dashboard",
 "tags": [
  "prod",
  "tv"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{kubernetes_cluster=~\"prod\\\\d*\",pod=~\".+\"})"
    }
   ]
  },
  {
   "title": "Hermes Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{kubernetes_cluster=~\"prod\\\\d*\",pod=~\"hermes-api.+\"})"
    }
   ]
  },
  {
   "title": "~API Traffic Req/Min",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{kubernetes_cluster=~\"prod\\\\d*\",service=\"hermes-api\"}[2m])*60)"
    }
   ]
  }
 ]
}