{
 "title": "Infrastructure workers and controllers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   { "name": "env", "label": "Enviroment", "query": "label_values(env)" }
  ]
 },
 "panels": [
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{kubernetes_cluster=\"$cluster\", node=~\"$cluster-worker\\\\d\\\\d\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Workers Down",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{kubernetes_cluster=\"$cluster\", node=~\"$cluster-worker\\\\d\\\\d\"}) / sum(kube_node_info{kubernetes_cluster=\"$cluster\", node=~\"$cluster-worker\\\\d\\\\d\"} offset 1d)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_uname_info{env=\"$env\", nodename=~\"$cluster-worker\\\\d\\\\d\"}) / sum(node_uname_info{env=\"$env\", nodename=~\"$cluster-worker\\\\d\\\\d\"} offset 1d)"
    }
   ]
  }
 ]
}