{
 "title": "Barclays Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hermes_current_users_total{kubernetes_cluster=\"prod0\", client_app=\"Barclays Mobile Banking\"}"
    }
   ]
  },
  {
   "title": "Number of payment cards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hermes_current_payment_cards_total{kubernetes_cluster=\"prod0\", client_app=\"Barclays Mobile Banking\"}"
    }
   ]
  },
  {
   "title": "Number of membership cards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hermes_current_membership_cards_total{kubernetes_cluster=\"prod0\", client_app=\"Barclays Mobile Banking\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "content": "## Number of users\nA count of the number of users who have consented to use the Bink service through Barclays.  If a user consents, deletes and consents again this will count as two.  This doesn't decrement when consent is removed.\n\n## Number of payment cards\nA count of payment card enrolments from Barclays.  This doesn't decrement when payment cards are deleted.\n\n## Number of membership cards\nA count of membership accounts added and joined through Barclays.  This doesn't decrement when membership cards are deleted.\n"
  }
 ]
}