{
 "title": "Barclays API Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   { "name": "channel", "label": "Channel", "query": "label_values(channel)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "content": "\n# HTTP Request Response Times\n\n\n- `/ubiquity/service`\n  - `GET` - A user getting info on their subscription to Bink\n  - `POST` - A user is subscribing to Bink\n  - `DELETE` - A user is unsubscribing from Bink\n- `/ubiquity/membership_plans`\n  - `GET` - Provides a list of Loyalty Schemes, unique to each channel\n- `/ubiquity/membership_cards`\n  - `GET` - Returns a list of all Loyalty Cards within a users wallet\n  - `POST` - Adds a new Loyalty Card to a users wallet\n- `/ubiquity/membership_card`\n  - `GET` - Returns details about a specific Loyalty Card within a users wallet\n  - `PATCH` - Updates the PLL relationship between a Loyalty Card and a Payment Card\n  - `DELETE` - Removes a Loyalty Card from a users wallet\n  - `PUT` - Update loyalty card\n- `/ubiquity/payment_cards`\n  - `GET` - Returns a list of all Payment Cards within a users wallet\n  - `POST` - Adds a new Payment Card to a users wallet\n- `/ubiquity/payment_card`\n  - `GET` - Returns details about a specific Payment Card within a users wallet\n  - `PATCH` - Updates the PLL relationship between a Payment Card and a Loyalty Card\n  - `DELETE` - Removes a Payment Card from a users wallet"
  },
  {
   "title": "Membership Cards - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_cards/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Cards - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_card/",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"POST\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-cards\", channel=\"$channel\", method=\"POST\"}[5m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Service - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/service/",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Service - DELETE",
   "type": "graph",
   "description": "endpoint: /ubiquity/service/",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"service\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Card - PUT",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_plans",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-card\", job=\"hermes\", channel=\"$channel\", method=\"PUT\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-card\", job=\"hermes\", channel=\"$channel\", method=\"PUT\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Card - DELETE",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_cards/",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"membership-card\", channel=\"$channel\", method=\"DELETE\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Payment Cards - POST",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_cards",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"POST\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Payment Cards - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/payment_cards",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", view=\"payment-cards\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "title": "Membership Plans - GET",
   "type": "graph",
   "description": "endpoint: /ubiquity/membership_plans",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-plans\", job=\"hermes\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\" , view=\"membership-plans\", job=\"hermes\", channel=\"$channel\", method=\"GET\"}[2m])) by (method, job, le))",
     "legendFormat": "{{method}} -- 95"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "content": "\n# HTTP Request Response Codes"
  },
  {
   "title": "GET",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"GET\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|retrieve-transactions|user-transactions|membership-card-transactions|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|retrieve-transactions|user-transactions|membership-card-transactions|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|retrieve-transactions|user-transactions|membership-card-transactions|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"GET\", status=~\"5\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|retrieve-transactions|user-transactions|membership-card-transactions|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"PUT\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new_login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new_login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"PUT\", status=~\"5\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60"
    }
   ]
  },
  {
   "title": "POST",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"POST\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new-login|new-register|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"POST\", status=~\"5\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new-login|new-register|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", method=\"DELETE\", job=\"hermes\", status=~\"2\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new_login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"3\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|new_login|register_user|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"4\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60",
     "legendFormat": "{{status}}--{{view}}"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_view_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", method=\"DELETE\", status=~\"5\\\\d\\\\d\", view=~\"membership-card|membership-cards|payment-card|payment-cards|service|membership-plans\", channel=\"$channel\"}[2m])) by (status, view) * 60"
    }
   ]
  }
 ]
}