{
 "title": "File Checks",
 "time": { "from": "now/d+10h", "to": "now/d-6h" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "content": "\n# Files from Merchant Schemes\n- `Iceland` - States whether we have received files today\n- `Harvey Nichols` - States whether we have received files today\n- `Wasabi` - States whether we have received files in the last 45 mins\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "content": "\n# Files from Payment Schemes\n- `Amex` - States whether we have received files today\n- `Mastercard` - States whether we have received files today\n\n\n"
  },
  {
   "title": "Iceland",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(blobstorage_files_total{name=\"iceland\"})"
    }
   ]
  },
  {
   "title": "Amex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(blobstorage_files_total{name=\"amex\"})"
    }
   ]
  },
  {
   "title": "Harvey Nichols",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(blobstorage_files_total{name=\"harvey-nichols\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mastercard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(blobstorage_files_total{name=\"mastercard\"})"
    }
   ]
  },
  {
   "title": "Wasabi",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blobstorage_files_total{name=\"wasabihack\"}[45m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}