{
 "title": "Loyalty Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   { "name": "scheme", "label": "Loyalty Scheme", "query": "label_values(scheme)" },
   { "name": "channel", "label": "Channel", "query": "label_values(channel)" }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "\n# Membership ADD" },
  {
   "title": "Enrol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Enrol\", scheme=\"$scheme\", channel=\"$channel\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Link",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Link\", scheme=\"$scheme\", channel=\"$channel\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Multi Wallet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Multi Wallet\", scheme=\"$scheme\", channel=\"$channel\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Wallet Only",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_add_total{kubernetes_cluster=\"$cluster\", route=\"Wallet Only\", scheme=\"$scheme\", channel=\"$channel\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 }, "content": "\n# Membership UPDATE" },
  {
   "title": "Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_update_total{route=\"Update\", kubernetes_cluster=\"$cluster\", channel=\"$channel\", scheme=\"$scheme\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Enrol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_update_total{route=\"Enrol\", kubernetes_cluster=\"$cluster\", channel=\"$channel\", scheme=\"$scheme\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Register",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(membership_card_update_total{kubernetes_cluster=\"$cluster\", channel=\"$channel\", scheme=\"$scheme\", route=\"Register\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}