{
 "title": "BPL Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Outbound Http requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(bpl_outgoing_http_requests_total{kubernetes_cluster=~\"prod0\"}[5m]))"
    }
   ]
  },
  {
   "title": "Inbound Http request Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bpl_inbound_http_request_total{kubernetes_cluster=~\"prod\\\\d\"}) by (retailer)",
     "legendFormat": "{{ retailer }}"
    }
   ]
  },
  {
   "title": "Inbound Http request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(bpl_inbound_http_request_latency_seconds_bucket{kubernetes_cluster=~\"prod\\\\d\"}[5m])) / 100",
     "legendFormat": "Prod (ms)"
    }
   ]
  },
  {
   "title": "Task Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "bpl_task_anomalies{kubernetes_cluster=~\"prod\\\\d\"}",
     "legendFormat": "Task Anomalies"
    }
   ]
  },
  {
   "title": "Erroneous Marketing opt out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bpl_erroneous_marketing_opt_out_get_requests_total{kubernetes_cluster=~\"prod\\\\d\"}",
     "legendFormat": "Erroneous Marketing opt out"
    }
   ]
  },
  {
   "title": "Tasks run total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "bpl_tasks_run_total{kubernetes_cluster=~\"prod\\\\d\"}",
     "legendFormat": "Tasks Run"
    }
   ]
  }
 ]
}