{
 "title": "Harmonia temp",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(files_received_total, kubernetes_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions Imported / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "transactions_total{kubernetes_cluster=\"$cluster\"}",
     "legendFormat": "{{transaction_type}} - {{ process_type }} - {{slug }} "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transactions_total{kubernetes_cluster=\"$cluster\"}) by (process_type, slug, transaction_type)",
     "legendFormat": "{{ process_type }} - {{slug }} - {{transaction_type}}"
    }
   ]
  },
  {
   "title": "Files received / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "files_received_total{kubernetes_cluster=\"$cluster\"}",
     "legendFormat": "{{ process_type }} - {{ slug }}"
    }
   ]
  },
  {
   "title": "Last processed file",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "max(last_file_timestamp) by (process_type, slug) * 1000",
     "legendFormat": "{{ process_type }} - {{slug}}"
    }
   ]
  }
 ]
}