{
 "title": "Hermes",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(django_http_requests_total_by_method_channel_view_and_response_status_total, kubernetes_cluster)"
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "label_values(django_http_requests_latency_seconds_by_view_method_count, channel)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Latency - $channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "repeat": "channel",
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "Average latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Request Latency - $channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "Average latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Request Latency - $channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "Average latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_cluster=\"$cluster\", job=\"hermes\", channel=\"${channel:raw}\"}[5m])) by (job, le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Requests per second (not split by channel :( )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_view_transport_method_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", view!~\"admin:.+|common\\\\.views\\\\.HealthCheck\"}[1m])) by(method, view)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Response status per second (not split by channel or view :( )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{kubernetes_cluster=\"$cluster\", job=\"hermes\", view!~\"admin:.+|common\\\\.views\\\\.HealthCheck\"}[1m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}