{
 "title": "Olympus Pod Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Application name", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 }, "content": "\n\n\n" },
  { "title": "Current Available Pods", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 6, "y": 0 }, "content": "\n" },
  { "title": "Total Pods", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 10, "y": 0 }, "content": "\n" },
  { "title": "Ready Pods", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 14, "y": 0 }, "content": "\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 }, "content": "\n# Hermes\n\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hermes-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"hermes-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 }, "content": "\n# Atlas\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"atlas-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"atlas-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 }, "content": "\n# Europa\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"europa-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"europa-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 }, "content": "\n# Hades\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"hades-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"hades-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 }, "content": "\n# Harmonia\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"harmonia-api\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"harmonia-api-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 }, "content": "\n# Iris\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"iris\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"iris\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"iris\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"iris-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 }, "content": "\n# Lethe\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"lethe\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"lethe\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"lethe\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"lethe-.+\", condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 }, "content": "\n# Metis\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"metis\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"metis\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"metis\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"metis-.+\", pod!~\"metis-celery-.+\" ,condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 17 }, "content": "\n# Midas\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"midas\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"midas\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"midas\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"midas-.+\", pod!~\"midas-celery-.+\" ,condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 19 }, "content": "\n# Thanatos\n\n" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"thanatos\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"thanatos\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"thanatos\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"thanatos-.+\", pod!~\"thanatos-celery-.+\", pod!~\"thanatos-migrator-.+\",condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 }, "content": "\n# Policies\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"policies\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"policies\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"policies\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"policies-.+\",condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 }, "content": "\n# Zephyrus\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"zephyrus\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"zephyrus\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"zephyrus\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"zephyrus-.+\",condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 }, "content": "\n# Zeus\n\n" },
  {
   "title": "Current Available Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_cluster=\"prod0\", deployment=\"zeus\"} / kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"zeus\"}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_cluster=\"prod0\", deployment=\"zeus\"}",
     "legendFormat": "Hermes Pods"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{kubernetes_cluster=\"prod0\", pod=~\"zeus-.+\",condition=\"true\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}